### ISSUE TITLE
compiling problems

### ISSUE THREAD

**Issue by vanderleisp** [pequots34/Forecast#3]
Trying to test your code, and seems it isn't a problem inside your code, but always that I try to compile it then I get error as below:

Error:Execution failed for task ':Forecast:dexDebugTest'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
	C:\xx\xx\AppData\Local\Android\sdk\build-tools\19.1.0\dx.bat --dex --no-optimize --output C:\xx\forecast\Forecast-master\Forecast-master\Forecast\build\intermediates\dex\test\debug C:\xx\forecast\Forecast-master\Forecast-master\Forecast\build\intermediates\classes\test\debug C:\xx\forecast\Forecast-master\Forecast-master\Forecast\build\intermediates\pre-dexed\test\debug\support-annotations-21.0.3-dd1a8f72c704401303dc992f577bc4cc3e173d49.jar C:\xx\forecast\Forecast-master\Forecast-master\Forecast\build\intermediates\pre-dexed\test\debug\classes-1046036228679a5833ced53388eb1154608d4a5d.jar C:\xx\forecast\Forecast-master\Forecast-master\Forecast\build\intermediates\pre-dexed\test\debug\internal_impl-21.0.3-eefaa5704cfc2bd94a84e52db78f1b5afaa05d15.jar C:\xx\forecast\Forecast-master\Forecast-master\Forecast\build\intermediates\pre-dexed\test\debug\android-support-v4-86b0248ea4f878fb2284c6ad3fb1dfc466e42331.jar C:\xx\forecast\Forecast-master\Forecast-master\Forecast\build\intermediates\pre-dexed\test\debug\classes-03388e7515bd8ebec90abd34e3e3aa1dbd24afe3.jar
Error Code:
	2
Output:
	UNEXPECTED TOP-LEVEL EXCEPTION:
	com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompatIcs;
		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:594)
		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:552)
		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:533)
		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:170)
		at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:439)
		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:287)
		at com.android.dx.command.dexer.Main.run(Main.java:230)
		at com.android.dx.command.dexer.Main.main(Main.java:199)
		at com.android.dx.command.Main.main(Main.java:103)

Seems it is something related to the Android Studio configuration, but after had spent half a day on this then got stuck.
any help ?

thanks,
Vanderlei

**Comment by pequots34** [comment]
updated to the latest version of gradle and android studio 1.0.+

NW-NEW:Forecast chbrown$ sh gradlew clean assembleDebug
:Forecast:clean
:Forecast:compileLint
:Forecast:copyDebugLint UP-TO-DATE
:Forecast:preBuild
:Forecast:preDebugBuild
:Forecast:checkDebugManifest
:Forecast:preDebugTestBuild
:Forecast:preReleaseBuild
:Forecast:prepareComAndroidSupportSupportV42103Library
:Forecast:prepareDebugDependencies
:Forecast:compileDebugAidl
:Forecast:compileDebugRenderscript
:Forecast:generateDebugBuildConfig
:Forecast:generateDebugAssets UP-TO-DATE
:Forecast:mergeDebugAssets
:Forecast:generateDebugResValues UP-TO-DATE
:Forecast:generateDebugResources
:Forecast:mergeDebugResources
:Forecast:processDebugManifest
:Forecast:processDebugResources
:Forecast:generateDebugSources
:Forecast:compileDebugJava
:Forecast:extractDebugAnnotations
:Forecast:mergeDebugProguardFiles UP-TO-DATE
:Forecast:processDebugJavaRes UP-TO-DATE
:Forecast:packageDebugJar
:Forecast:compileDebugNdk
:Forecast:packageDebugJniLibs UP-TO-DATE
:Forecast:packageDebugLocalJar UP-TO-DATE
:Forecast:packageDebugRenderscript UP-TO-DATE
:Forecast:packageDebugResources
:Forecast:bundleDebug
:Forecast:assembleDebug

BUILD SUCCESSFUL

Total time: 7.106 secs
NW-NEW:Forecast chbrown$
