### ISSUE TITLE
Search weather by city name

### ISSUE THREAD

**Issue by nurzhannogerbek** [pequots34/Forecast#4]
Hello! First of all I need to say that it is very interesting project. Anyway I want to know one thing. Is it possible to know weather in forecast.oi by name of location(London, Tokyo, e.t.c.) As I understand here you can know it only with LATITUDE,LONGITUDE. Thanks for attention and have a nice day!

**Comment by pequots34** [comment]
I would have to double check the api spec. When the library was originally implemented they didn't have a way to do that. In the short term you can wrap the request in your own async task and reverse lookup the location ( geocoder ). We are in the process of upgrading the library to gradle 2.4 and adding new features. A preview release will be coming soon. Please let us know if you have any feature requests.
